### ISSUE TITLE
Apostille Library Specification

### ISSUE THREAD

**Issue by gimyboya** [nemtech/NIP#2]
# NIP-? - Apostille Library Specification

## Summary

```
	NIP: ?
	Layer:  Library
	Title: Apostille Library Specification
	Author: 
	* Discussions-To: <telegram group>
	Comments-URI: 
	Status: Draft
	Type: Standards Track
	Created: 2018-03-15
	License: MIT
```
## Introduction/Abstract
NEM Apostille is a standard that enables a very versatile blockchain certificate system. It is used for a variety of use cases including the following: 

1) proof of existence for real world and digital products, 
2) certificates of ownership and operation for IOT devices, 
3) use the blockchain to show chain-of-custody and/or supply chain projects
4) providing on-chain certificates, diplomas, land titles, ID where the entire certificate is represented on the blockchain and is transferable and updatable. 
5) and more...

The key innovation of Apostille is the realization that every item can be given its own private key, and that private key can be used to make a container address to record data about the item, have value sent to and from the item, and taking advantage of NEM's advanced multisig be used to even transfer ownership of the item's container on-chain from person to person.  

This is an evolutionary leap from other blockchain notarization applications which often just record a fingerprint or hash of a document to show that it exists. 

Also, due to the nature of NEM's architecture, few if any other blockchains can reproduce the utility unlocked by the NEM Apostille Standard. 

## Motivation

Apostille protocol and standards are an advanced way of using NEM blockchain for notarization purposes. and it is crucial to have a dedicated library that clearly documents the protocol and its standards with the hope of getting future contributions improving upon this standard.

## Specification

: required

The technical specification should describe the syntax and semantics of any new feature. The specification should be detailed enough to allow competing, interoperable implementations for any of the current components.

## Design Decisions

: required

Discuss design decisions (including, as examples):

- Reason about the correctness of the implementation.
- "Feel and fit" with existing core libraries.
- Performance and threading considerations.
- Potential conflicts with existing libraries, e.g. name clashes, IDE auto-import friction, etc.

The rationale fleshes out the specification by describing what motivated the design and why particular design decisions were made. It should describe alternate designs that were considered and related work. The rationale should provide evidence of consensus within the community and discuss important objections or concerns raised during the discussion.

## Implementation

[Apostill-library](https://github.com/gimyboya/Apostille-library) repository can be found here

## Backwards compatibility

Even though the `apostille-library` will be designed for a broader range of use cases and to be able to handle real life assets which can be used in different setups and environments, it will still keep it's ability to audit `.nty` files which are the Nanowallet representation of an Apostille (digital file).

However the `apostille-library` may design different types of representation of an Apostille.

Also since the NanoWallet implementation was using the `crypto-js` library for SHA3 hash function (which is the old algorithm Keccak [source](https://code.google.com/archive/p/crypto-js/) ) we are going to keep the possibility to use KECCAK for backward compatibility by renaming it to KSHA3 or simply KECCAK and providing the NIST SHA3 standards by incrementing the signed and non-signed bites in the checksum which will allow the use of SHA3 for the future usage of the library and KECCAK for backward compatibility.

[More info about KECCAK and SHA3](https://medium.com/@ConsenSys/are-you-really-using-sha-3-or-old-code-c5df31ad2b0)

## Drawbacks

As a second layer standard and protocol, the Apostille Library could be

1. implemented incorrectly by third-party developers.
2. could be implemented in incompatible ways.
3. more feedback from industry partners is needed to clearly define the standard.

## References

White Paper: https://nem.io/wp-content/themes/nem/files/ApostilleWhitePaper.pdf
Project Site: https://nem.io/project/apostille/

## History

| **Date**   | **Version**   |
| ---------- | ------------- |
| 2018-03-15 | Initial Draft |

**Comment by gimyboya** [comment]
This issue was initially created (here)[https://github.com/NemProject/NIP/issues/3] and was closed in favors of the current one here.

@aleixmorgadas @dgarcia360 @jabo38

**Comment by dgarcia360** [comment]
To include the NIP in the repository and assign a number, the following must be achieved:

- **NIP must sound complete:** Specification and Design Decisions sections are missing or under construction.
- **Tite describes  the content accurately**: ✓
- **NIP draft has been published as an issue**: ✓
- **Motivation and backward compatibility must be addressed**:  backwards compatibility is missing. You could reference how the proposed library will be able to handle previously apostilled documents.
- **Header is correct**: `Layer` should go after `Type`. Delete `*` symbols.
* Licensing terms are acceptable** ✓

**Comment by aleixmorgadas** [comment]
Looking into implementation of `sha3-512` of Apostille Library ([link](https://github.com/NEM-Apostille/Apostille-library/blob/master/src/hashFunctions/sha3-512.ts)).

I think you are merging two different concepts, SHA3 is a well-known hash function and how it behaves. For example, the `apostille-library` implementation just expects a string as input, meanwhile, sha3 allows other formats, like ByteArray.

On the other hand, the hash function is also signing the data, it feels weird... we should spend some time designing the class.

In the specification section, should appear things like why `const CHEKSUM = 'fe4e5459' + this.signed;`, [source](https://github.com/NEM-Apostille/Apostille-library/blob/master/src/hashFunctions/sha3-512.ts#L14).

:warning: You have to replace the dependency of `nem-sdk` by `nem2-sdk`. If `nem2-sdk` doesn't allow you to get that working, we could make it work.

Also, the [file names](https://github.com/NEM-Apostille/Apostille-library/tree/master/src/hashFunctions) don't follow a pattern.

**Comment by gimyboya** [comment]
@aleixmorgadas Thank you for taking the time to review the code I appreciate it!
i am following the section 3.4 form the [Apostille white paper](https://nem.io/wp-content/themes/nem/files/ApostilleWhitePaper.pdf) where we need to create a hash of the file being notarized (this works best with digital files) however in the paper the hash looks something like this `ApostilleHash = Apostille header + fileContentHash;`

as for the rest of the logic (what does the checksum mean and why the data is signed) it's explained here
![hash](https://i.imgur.com/lQGX9my.png)

Now with that we diffidently need to support other types like word array and byte array that are supported by the hash function. my idea was that i need to get something stable first before adding support for other types.

The signing of the data is following the private Apostille protocol as mentioned in the white paper.. not sure if you mean that we should use a different naming convention?

I will try to comment the logic behind the functioning of the library in fact i will have to go through the whole code and comment it properly ( not sure if this should be done in parallel)

Yes Please! the current sign function in `nem2-sdk` accepts a transaction only whereas in `nem-sdk` it can sign anything that we feed it, unless i can sign raw data with `Account.sign()` i can't use it here.

Finally regarding the file names i don't really get what you mean could you please give an example or a suggestion?

**Comment by aleixmorgadas** [comment]
which is the benefit of multiple hashing functions? more in particular MD5, SHA1?

one particularity that `nem2-sdk` has is that uses SHA3 for private network and Keccak for the public network.

**Comment by gimyboya** [comment]
I think the different hashes functions are just available to provide more options. maybe @jabo38 can tell something that i am overlooking here.

as for the implementation of SHA3 i think i am using Keccak and not SHA3 since i am using `crypto-js` library which if i recall it uses the Keccak implementation (please correct me if i am wrong). if we change it to SHA3 it may break the backward compatibility of auditing previous Apostilles.

As for backward compatibility in general.. i would say this library is covering a lot of use cases that the old version of Apostille was locking because it was focused on digital files and NanoWallet use cases which makes the implementation different however i will try to make it possible to audit and verify an Apostille file from NanoWallet.

**Comment by aleixmorgadas** [comment]
> if we change it to SHA3 it may break the backward compatibility of auditing previous Apostilles.

Let's put explicitly that you use `Keccak` in `MAIN NET`, `0x88` & `0x89`. Then, you could assign a  new key pair to `SHA3`, like `0x8A` & `0x8B` (or choose which you prefer). Nowadays, we differentiate between Keccak and SHA3, it could let into errors otherwise

**Comment by aleixmorgadas** [comment]
We should create backwards compatible solutions if possible and Apostille has already a good user base, we have to work to make it backwards compatible.

Without looking into it in detail, seems like it's not complex to accomplish.

**Comment by gimyboya** [comment]
Ok if that's the case i will keep backwards compatibility in mind.
However If we put Keccak for `MAIN_NET` it will be a temporary solution in the sense that if Catapult will be released in `MAIN_NET` one day, our code will always be using old code Keccak isn't better to just provide a new hash function SHA3 with new signing bites and we name the old one KSHA3?

This way we keep backward compatibility but we also open the possibility to have SHA3 in the `MAIN_NET` for future Apostilles.

**Comment by gimyboya** [comment]
To include the NIP in the repository and assign a number, the following must be achieved:

- **NIP must sound complete:** Specification and Design Decisions sections are missing or under construction.
- **Title describes the content accurately:** ✓
- **NIP draft has been published as an issue:** ✓
- **Motivation and backward compatibility must be addressed:** ✓
- **Header is correct:** ✓
- **Licensing terms are acceptable** ✓

**Comment by dgarcia360** [comment]
@gimyboya 

Correct, once initial specification and design decisions are complete, the NIP will be moved to the main repository as a draft NIP. 

Please, remember to update as well the pull-request with the latest changes.

**Comment by gimyboya** [comment]
@dgarcia360 Noted with many thanks.

**Comment by gimyboya** [comment]
regarding the naming convention of KECCAK should we name it KECCAK or KSHA3 ?

**Comment by aleixmorgadas** [comment]
KECCAK

**Comment by jabo38** [comment]
I’m scratching my head and trying to remember, but it could be one of the following.

1) Gimre told me to include multiple algorithms as some people might have a preference.

2) if I remember sha1 had a noticeably smaller hash output for the file fingerprint. People using it could still show proof of existence within reason but save of message cost and not bloat the Blockchain.

But really, I think that multiple algorithms were when we were doing “public” timestamps which essentially was a proof of existence.

What Apostille ended up being really was the “private” Apostilles where each file got not only a fingerprint but its own private key.

If I had to do it all over again, I’d probably remove the public timestamp option altogether and just make every Apostille it’s own container account.

Sent from my iPhone

On 3 May 2018, at 2:56 AM, Aleix Morgadas <notifications@github.com<mailto:notifications@github.com>> wrote:


KECCAK

**Comment by dgarcia360** [comment]
@gimyboya I would like to know if you will be continuing this NIP, or if do you think that makes sense to continue with #11

**Comment by dgarcia360** [comment]
Closed due to inactivity.
